# Brightness
bindel = ALT, Page_Up, exec, ~/.config/hypr/dms/ddcfast_osd.sh brightness +5 --display DP-1 --scale 0.75
bindel = ALT, Page_Down, exec, ~/.config/hypr/dms/ddcfast_osd.sh brightness -5 --display DP-1 --scale 0.75
bindel = , XF86MonBrightnessUp, exec, ~/.config/hypr/dms/ddcfast_osd.sh brightness +5 --display DP-1 --scale 0.75
bindel = , XF86MonBrightnessDown, exec, ~/.config/hypr/dms/ddcfast_osd.sh brightness -5 --display DP-1 --scale 0.75

# Contrast
bindel = ALT SHIFT, Page_Up, exec, ~/.config/hypr/dms/ddcfast_osd.sh contrast +5 --display DP-1
bindel = ALT SHIFT, Page_Down, exec, ~/.config/hypr/dms/ddcfast_osd.sh contrast -5 --display DP-1
